#!/bin/bash
#
# A shell script to copy the generated binary image to the ISP virtual USB disk.
# Can be added to lpcxpresso as an external tool.
#

# Binary file generated by lpcxpresso.
src="./Debug/hello_world.bin"

# Location of the firmware file in the USB ISP virtual disk.
dst="/Volumes/CRP DISABLD/firmware.bin"

echo "Will copy ${src} to ${dst}"

while [ ! -f "${dst}" ]
do
  echo "Waiting for ${dst}"
  ls -l "${dst}"
  sleep 2
done

ls -l "${dst}"
echo "Copying ..."
cp "${src}" "${dst}"
ls -l "${dst}"
echo "Exiting."

