#!/bin/bash
#
# A Max OSX shell script to copy the generated binary image of the current
# project to the ISP virtual USB disk. Can be added to lpcxpresso as an
#  external tool that builds the project before running this script.
#

echo "Working directory: $PWD"

# Set lpcxpresso to provide these two variables with the name and
# absolute path of the current project.
#
# Location field:
# ${workspace_loc:/arm_pro_mini_lib/tools/copy_bin_to_usb_isp.sh}
#
# Arguments field:
# ${project_name} ${project_loc} ${config_name:${project_name}}
#
# Selected in Build tab:
# * Build before launch.
# * The project containing the selected resource.
# * Include referenced projects
# 

# E.g. 'hello_world'
project_name="$1"

# Absolute path to project's root.
project_loc="$2"

# E.g. 'Debug'
config_name="$3"

echo
echo "Project name: [${project_name}]"
echo "Project loc: [${project_loc}]"
echo "Config name: [${config_name}]"

# axf file from which the .bin is generated. If it doesn't exist then the
# .bin file is not current.
#
# TODO: add a test that if the .axf file exists, it's not newer than the 
# .bin file. Can use the command 'stat -f "%m" <file_name>' to get a file's
# timestamp in seconds.
axf_src="${project_loc}/${config_name}/${project_name}.axf"

if [ ! -f "${axf_src}" ]; then
  echo
  echo "${project_name}.axf doesn't exist. Assuming build failed."
  echo "ABORT".
  exit 1
fi

# Binary file generated by lpcxpresso.
bin_src="${project_loc}/${config_name}/${project_name}.bin"

# Location of the firmware file in the USB ISP virtual disk.
bin_dst="/Volumes/CRP DISABLD/firmware.bin"

echo "Will copy ${bin_src} to ${bin_dst}"

while [ ! -f "${bin_dst}" ]
do
  echo
  echo "Waiting for ${bin_dst}"
  ls -l "${bin_dst}"
  sleep 2
done

# An ISP session can accept an image file only once. Verify that we didn't
# already written in this ISP session. We do it by checking the timestamp
# of the file. If it is a fresh invocation it should have an old timestamp.
dst_timestamp=`stat -f "%m" "${bin_dst}"`
echo "Destination file timestamp: ${dst_timestamp}"
if (( ${dst_timestamp} > 1400000000  )); then
  echo "Require a fresth activation of ISP mode. Press ISP button and retry."
  echo "ABORT".
  exit 
fi

echo
ls -l "${bin_dst}"
echo "Copying ..."
cp "${bin_src}" "${bin_dst}"
ls -l "${bin_dst}"
echo
echo "PROGRAMMED OK."

